#ifndef CANTIL_LOGGER_EXCEPT_H
#define CANTIL_LOGGER_EXCEPT_H

#include "cn/logger/except.h"

#define EXCEPTIONS_EN CN_EXCEPTIONS_EN

#define ENSURE CN_ENSURE

#define RAISE CN_RAISE

#define ENSURE_MEMORY CN_ENSURE_MEMORY

#endif /* CANTIL_LOGGER_EXCEPT_H */
