ub-algo-blddir := $(blddir)/$(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))
ub-blddirs += $(ub-algo-blddir)

ub-objs += $(ub-algo-blddir)/binode.o
ub-objs += $(ub-algo-blddir)/list.o
ub-objs += $(ub-algo-blddir)/pool.o
ub-objs += $(ub-algo-blddir)/rbtree.o
ub-objs += $(ub-algo-blddir)/strnode.o
ub-objs += $(ub-algo-blddir)/waitq.o
