algo_blddir := $(blddir)/$(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))

ub-blddirs += $(algo_blddir)
ub-objs += $(algo_blddir)/binode.o
ub-objs += $(algo_blddir)/list.o
ub-objs += $(algo_blddir)/pool.o
ub-objs += $(algo_blddir)/rbtree.o
ub-objs += $(algo_blddir)/strnode.o
ub-objs += $(algo_blddir)/waitq.o
