@startuml "Modules hierarchy"

package "Standard libraries" {
    [stdio]
    [stdlib]
    [pthread]
}

component [vertegs]
component [basis]
component [osal]
component [logger]
component [algo]
component [broker]

broker --> vertegs
broker --> osal
broker --> logger
broker --> algo
algo --> vertegs
algo --> osal
algo --> logger
logger --> vertegs
logger --> osal
osal --> basis
osal --> stdio
osal --> stdlib
osal --> pthread
basis --> vertegs

@enduml
