@startuml "Broker data types"

class Broker {
    -channels : Dictionary<string, Channel>
    -subscribers : Set<Subscriber>
    -pool : Set<Message>
    +<<Create>> create(in payload_size : size_t)
    +<<Destroy>> destroy()
    +search(in topic : string) : Channel
    +adjust(in n : int) : int
}

class Channel {
    -topic : string
    +gettopic() : string
}

class Message {
    +payload : void*
    -channel : Channel
    +<<Create>> alloc(in ch : Channel)
    +<<Create>> tryalloc(in ch : Channel)
    +<<Destroy>> publish()
    +setcb(in cb : void (*)())
    +getchannel() : Channel
}

class Subscriber {
    -last_msg : Message
    +<<Create>> create(in broker : Broker)
    +<<Destroy>> destroy()
    +subscribe(in topic : string)
    +await() : Message
    +poll() : Message
    +unload()
}

Subscriber --> Message
Message --> Channel
Message "many" --o "1" Broker
Channel "many" --o "1" Broker
Subscriber "many" --o "1" Broker
Subscriber --> Broker

@enduml
