@startuml "Broker data types"

abstract class MessageVtable {
    +size()
    +ctor(in args : va_list) : void*
    +dtor(in msg : void*)
}

class Broker {
    -channels : Dictionary<char*, Channel>
    -subscribers : List<Subscriber>
    +create(in vp : MessageVtable)
    +search(in topic : char*) : Channel
}

class Channel {
    +publish(in args : ...)
    +gettopic() : char*
}

class Subscriber {
    +create(in broker : Broker)
    +subscribe(in topic : char*)
    +await() : void*
    +poll() : void*
    +unload()
}

Channel "many" --o "1" Broker
Broker --> MessageVtable
Subscriber "many" --o "1" Broker
Subscriber --> Broker

@enduml
