name: Deploy

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        sudo apt update
        sudo apt-get install doxygen
        sudo apt-get install graphviz
    - name: Generate docs
      run: tools/picky.sh make public
    - name: Deploy Doxygen Docs
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public/html
